### ISSUE TITLE
Invocation Name of the AlexaDronePilote

### ISSUE THREAD

**Issue by violivei** [jose-troche/AlexaDronePilot#1]
Hello,

I really want to test your work. However, it's not clear which invocation name needs to be used when adding a new skill on Alexa Console.

Thanks in advance.

**Comment by jose-troche** [comment]
You have to create a new Alexa Skill Set https://developer.amazon.com/edw/home.html#/skills

If you want to know how to build your first skill follow this: https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit#get-started-now.

You can use the files under https://github.com/jose-troche/AlexaDronePilot/tree/master/alexaApp to build the app. Use the id of lambda function created from the AWS lambda console.

Once you do that, just say "Alexa start drone pilot.."

**Comment by wesgruver** [comment]
Jose, anyway you can share the code you uploaded for your Lambda function?

**Comment by jose-troche** [comment]
@wesgruver The function is already in the source code https://github.com/jose-troche/AlexaDronePilot/blob/master/alexaApp/lambda.index.js
